# Generated by Django 2.2.1 on 2020-09-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('phone', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('advice', models.EmailField(max_length=100, verbose_name='email')),
            ],
        ),
    ]
