# Generated by Django 2.2.1 on 2019-08-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('phase', models.TextField(blank=True, null=True)),
                ('condation', models.TextField(blank=True, null=True)),
                ('intervention', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'info_clinical',
            },
        ),
        migrations.CreateModel(
            name='InfoClinical2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('phase', models.TextField(blank=True, null=True)),
                ('condation', models.TextField(blank=True, null=True)),
                ('intervention', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'info_clinical2',
            },
        ),
        migrations.CreateModel(
            name='InfoDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.TextField(blank=True, db_column='Drug_Name', null=True)),
                ('other_drug_names', models.TextField(blank=True, db_column='Other_Drug_Names', null=True)),
                ('originator_company', models.TextField(blank=True, db_column='Originator_Company', null=True)),
                ('active_companies', models.TextField(blank=True, db_column='Active_Companies', null=True)),
                ('active_indications', models.TextField(blank=True, db_column='Active_Indications', null=True)),
                ('target_based_actions', models.TextField(blank=True, db_column='Target_based_Actions', null=True)),
                ('highest_status', models.TextField(blank=True, db_column='Highest_Status', null=True)),
                ('technologies', models.TextField(blank=True, db_column='Technologies', null=True)),
                ('total_reported_sales_2014_usd_m', models.TextField(blank=True, db_column='Total_Reported_Sales_2014_USD_M', null=True)),
                ('total_forecast_sales_2020_usd_m', models.TextField(blank=True, db_column='Total_Forecast_Sales_2020_USD_M', null=True)),
                ('inactive_companies', models.TextField(blank=True, db_column='Inactive_Companies', null=True)),
                ('inactive_indications', models.TextField(blank=True, db_column='Inactive_Indications', null=True)),
                ('other_actions', models.TextField(blank=True, db_column='Other_Actions', null=True)),
                ('last_change_date', models.TextField(blank=True, db_column='Last_Change_Date', null=True)),
            ],
            options={
                'db_table': 'info_drug',
            },
        ),
        migrations.CreateModel(
            name='NPassay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_type_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_value', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_units', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source_db', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'np_assay',
            },
        ),
        migrations.CreateModel(
            name='NpDbLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_inchi', models.TextField(blank=True, null=True)),
                ('standard_inchi_key', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_smiles', models.TextField(blank=True, null=True)),
                ('slogp', models.FloatField(blank=True, db_column='SlogP', null=True)),
                ('tpsa', models.FloatField(blank=True, db_column='TPSA', null=True)),
                ('amw', models.FloatField(blank=True, db_column='AMW', null=True)),
                ('numrotatablebonds', models.SmallIntegerField(blank=True, db_column='NumRotatableBonds', null=True)),
                ('numhbd', models.SmallIntegerField(blank=True, db_column='NumHBD', null=True)),
                ('numhba', models.SmallIntegerField(blank=True, db_column='NumHBA', null=True)),
                ('numheavyatoms', models.SmallIntegerField(blank=True, db_column='NumHeavyAtoms', null=True)),
                ('numrings', models.SmallIntegerField(blank=True, db_column='NumRings', null=True)),
            ],
            options={
                'db_table': 'np_db_local',
                'ordering': ['database_id'],
            },
        ),
        migrations.CreateModel(
            name='NPderivativeassay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivative_id', models.CharField(blank=True, max_length=255, null=True)),
                ('molecule_chembl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_relation', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_value', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_units', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source_db', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'np_derivative_assay',
            },
        ),
        migrations.CreateModel(
            name='NPderivativeid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.CharField(blank=True, max_length=255, null=True)),
                ('derivative_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'np_derivative_id',
            },
        ),
        migrations.CreateModel(
            name='NPDtargetinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pref_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organism', models.CharField(blank=True, max_length=255, null=True)),
                ('target_chembl_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'np_target_info',
            },
        ),
        migrations.CreateModel(
            name='NPenglishnamecas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.CharField(blank=True, max_length=255, null=True)),
                ('iupac_name', models.TextField(blank=True, null=True)),
                ('pref_name', models.TextField(blank=True, null=True)),
                ('cas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'np_english_name_cas',
                'ordering': ['database_id'],
            },
        ),
        migrations.CreateModel(
            name='NPidinotherdatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_inchi_key', models.CharField(blank=True, max_length=255, null=True)),
                ('chembl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pubchem_cid', models.CharField(blank=True, max_length=255, null=True)),
                ('np_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'np_id_in_other_database',
                'ordering': ['database_id'],
            },
        ),
        migrations.CreateModel(
            name='PhaseDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.TextField(blank=True, null=True)),
                ('condation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'info_PhaseDistribution',
            },
        ),
        migrations.CreateModel(
            name='TargetDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_indications', models.TextField(blank=True, db_column='Active_Indications', null=True)),
                ('target_based_actions', models.TextField(blank=True, db_column='Target_based_Actions', null=True)),
            ],
            options={
                'db_table': 'info_TargetDistribution',
            },
        ),
    ]
