# Generated by Django 2.2.1 on 2020-07-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_chemicalindex_clinicaldata_clinicaldatabig_extract_fdadrug_fdadrugorangebook_fdapatent_genericdrugda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicalData',
        ),
        migrations.DeleteModel(
            name='Extract',
        ),
        migrations.DeleteModel(
            name='YearEndData',
        ),
        migrations.RemoveField(
            model_name='inactiveingredientsearch',
            name='record_updated',
        ),
    ]
