# Generated by Django 2.2.1 on 2020-08-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200712_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicaldetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.TextField(blank=True, null=True)),
                ('last_refreshed_on', models.TextField(blank=True, null=True)),
                ('secondary_id', models.TextField(blank=True, null=True)),
                ('public_title', models.TextField(blank=True, null=True)),
                ('scientific_title', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('study_type', models.TextField(blank=True, null=True)),
                ('study_design', models.TextField(blank=True, null=True)),
                ('phase', models.TextField(blank=True, null=True)),
                ('date_of_registration', models.TextField(blank=True, null=True)),
                ('date_of_first_enrolment', models.TextField(blank=True, null=True)),
                ('target_sample_size', models.TextField(blank=True, null=True)),
                ('recruitment_status', models.TextField(blank=True, null=True)),
                ('primary_sponsor', models.TextField(blank=True, null=True)),
                ('secondary_sponsor', models.TextField(blank=True, null=True)),
                ('source_of_monetary_support', models.TextField(blank=True, null=True)),
                ('countries_of_recruitment', models.TextField(blank=True, null=True)),
                ('health_condition_or_problem_studied', models.TextField(blank=True, null=True)),
                ('intervention', models.TextField(blank=True, null=True)),
                ('age_minimum', models.TextField(blank=True, null=True)),
                ('age_maximum', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('key_inclusion_exclusion_criteria', models.TextField(blank=True, null=True)),
                ('primary_outcome', models.TextField(blank=True, null=True)),
                ('secondary_outcome', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinical_detail',
            },
        ),
    ]
