# Generated by Django 2.2.1 on 2020-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_clinicalbrowse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalbrowse',
            options={'ordering': ['date_of_registration']},
        ),
        migrations.AlterModelOptions(
            name='clinicaldetail',
            options={'ordering': ['date_of_registration']},
        ),
        migrations.AddField(
            model_name='clinicalbrowse',
            name='phase',
            field=models.TextField(blank=True, null=True),
        ),
    ]
