# Generated by Django 2.2.1 on 2020-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_phasedistribution_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetdistribution',
            name='drug_name',
            field=models.TextField(blank=True, db_column='drug_name', null=True),
        ),
    ]
