# Generated by Django 2.2.1 on 2020-09-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_infodrug2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoDrug2',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='active_companies',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='active_indications',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='drug_name',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='highest_status',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='inactive_companies',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='inactive_indications',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='last_change_date',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='originator_company',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='other_actions',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='other_drug_names',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='target_based_actions',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='total_forecast_sales_2020_usd_m',
        ),
        migrations.RemoveField(
            model_name='infodrug',
            name='total_reported_sales_2014_usd_m',
        ),
        migrations.AddField(
            model_name='infodrug',
            name='Active_Indications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='Target_based_Actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='canonical_smiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='chembl_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='first_approval',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='max_phase',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='molecule_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='molregno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='pref_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='standard_inchi_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infodrug',
            name='structure_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
