# Generated by Django 2.2.1 on 2020-09-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_auto_20200922_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infodrug',
            old_name='molregno',
            new_name='name',
        ),
    ]
